project_id = "wjnermhmkuoqusnxppiu"

[functions.send-contact-email]
verify_jwt = false

[functions.send-client-email]
verify_jwt = false

[functions.send-onboarding-email]
verify_jwt = false

[functions.drgreen-webhook]
verify_jwt = false

[functions.drgreen-health]
verify_jwt = false