project_id = "swjifcjdrqtbupoibyfn"

[functions.admin-update-user]
verify_jwt = true

[functions.drgreen-health]
verify_jwt = false

[functions.drgreen-proxy]
verify_jwt = false

[functions.drgreen-webhook]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.batch-generate-images]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.prescription-expiry-check]
verify_jwt = true

[functions.seed-test-users]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.strain-knowledge]
verify_jwt = false

[functions.strain-medical-info]
verify_jwt = false

[functions.sync-strains]
verify_jwt = true
